In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [ ]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [ ]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.shape

(10000, 11)

In [ ]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

In [ ]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [ ]:
x= df.drop('Exited', axis=1)
y= df['Exited']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_trf = scaler.fit_transform(x_train)
x_test_trf = scaler.transform(x_test)

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(11, activation='relu',input_dim=11))
model.add(Dense(12, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           130 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 417 (1.63 KB)

 Trainable params: 417 (1.63 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(x_train, y_train, batch_size=50, epochs=100,verbose=1, validation_split=0.2)

Epoch 1/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.4958 - loss: 2375.8972 - val_accuracy: 0.6744 - val_loss: 57.6941
Epoch 2/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7176 - loss: 52.6221 - val_accuracy: 0.7775 - val_loss: 20.7825
Epoch 3/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6994 - loss: 22.3155 - val_accuracy: 0.6812 - val_loss: 7.8104
Epoch 4/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6598 - loss: 10.5553 - val_accuracy: 0.6925 - val_loss: 4.6248
Epoch 5/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6537 - loss: 10.0889 - val_accuracy: 0.3994 - val_loss: 29.7732
Epoch 6/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6799 - loss: 16.0401 - val_accuracy: 0.6619 - val_loss: 1.5608
Epoch 7/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6920 - loss: 6.7432 - val_accuracy: 0.4712 - val_loss: 9.3912
Epoch 8/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6739 - loss: 17.0597 - val_accuracy: 0.2419 - val_loss: 16.4334
Epoch 9/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6619 - loss: 13.1194 - val_accuracy: 0.7987 - val_loss: 44.1785
Epoch 10/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6895 - loss: 19.0818 - val_accuracy: 0.7956 - val_loss: 3.8432
Epoch 11/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6826 - loss: 7.8534 - val_accuracy: 0.5219 - val_loss: 1.5694
Epoch 12/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6561 - loss: 10.3232 - val_accuracy: 0.7987 - val_loss: 14.2696
Epoch 13/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6624 - loss: 14.0279 - val_accuracy: 0.7987 - val_loss: 28.4013
Epoch 14/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7021 - loss: 13.6612 - val_accuracy: 0.7962 - val_loss: 4.3922
Epoch 15/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6857 - loss: 10.0552 - val_accuracy: 0.7987 - val_loss: 20.9762
Epoch 16/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6824 - loss: 12.2739 - val_accuracy: 0.7987 - val_loss: 13.7915
Epoch 17/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6890 - loss: 8.5361 - val_accuracy: 0.4644 - val_loss: 4.4416
Epoch 18/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6729 - loss: 13.3751 - val_accuracy: 0.7994 - val_loss: 5.8664
Epoch 19/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6840 - loss: 7.0674 - val_accuracy: 0.7987 - val_loss: 11.1211
Epoch 20/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6874 - loss: 10.4301 - val_accuracy: 0.7894 - val_loss: 2.1624
Epoch 21/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6829 - loss: 8.9718 - val_accuracy: 0.3125 - val_loss: 11.8452
Epoch 22/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6686 - loss: 10.7876 - val_accuracy: 0.6700 - val_loss: 8.9892
Epoch 23/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6864 - loss: 8.9138 - val_accuracy: 0.7987 - val_loss: 8.2682
Epoch 24/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6787 - loss: 10.3459 - val_accuracy: 0.3369 - val_loss: 22.5562
Epoch 25/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6574 - loss: 12.9573 - val_accuracy: 0.5881 - val_loss: 2.1055
Epoch 26/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6661 - loss: 6.7427 - val_accuracy: 0.7987 - val_loss: 6.4244
Epoch 27/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6725 - loss: 7.2876 - val_accuracy: 0.3031 - val_loss: 22.2431
Epoch 28/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6752 - loss: 10.8211 - val_accuracy: 0.7987 - val_loss: 2.7543
Epoch 29/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6816 - loss: 8.7042 - val_accuracy: 0.4769 - val_loss: 13.3369
Epoch 30/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6655 - loss: 10.8829 - val_accuracy: 0.7925 - val_loss: 4.8680
Epoch 31/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6865 - loss: 5.1614 - val_accuracy: 0.7987 - val_loss: 26.6921
Epoch 32/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6834 - loss: 11.0708 - val_accuracy: 0.2438 - val_loss: 9.6141
Epoch 33/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6728 - loss: 9.4174 - val_accuracy: 0.2194 - val_loss: 22.6777
Epoch 34/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6539 - loss: 10.2617 - val_accuracy: 0.2512 - val_loss: 5.9827
Epoch 35/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6800 - loss: 5.5981 - val_accuracy: 0.7987 - val_loss: 3.9808
Epoch 36/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6717 - loss: 8.1467 - val_accuracy: 0.7769 - val_loss: 1.0939
Epoch 37/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6815 - loss: 8.2942 - val_accuracy: 0.7987 - val_loss: 49.6384
Epoch 38/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6913 - loss: 12.4055 - val_accuracy: 0.7987 - val_loss: 4.4024
Epoch 39/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6868 - loss: 5.4802 - val_accuracy: 0.7987 - val_loss: 18.5187
Epoch 40/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6840 - loss: 12.6174 - val_accuracy: 0.5675 - val_loss: 5.7432
Epoch 41/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6781 - loss: 5.8179 - val_accuracy: 0.5169 - val_loss: 4.3812
Epoch 42/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6860 - loss: 5.7904 - val_accuracy: 0.2275 - val_loss: 18.2232
Epoch 43/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6677 - loss: 9.4856 - val_accuracy: 0.2812 - val_loss: 11.1814
Epoch 44/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6615 - loss: 7.3308 - val_accuracy: 0.7987 - val_loss: 4.0622
Epoch 45/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6881 - loss: 9.3812 - val_accuracy: 0.7975 - val_loss: 17.6637
Epoch 46/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7130 - loss: 12.9249 - val_accuracy: 0.7981 - val_loss: 3.5450
Epoch 47/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6862 - loss: 8.5938 - val_accuracy: 0.7987 - val_loss: 5.2801
Epoch 48/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6955 - loss: 7.2381 - val_accuracy: 0.7931 - val_loss: 6.1375
Epoch 49/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6999 - loss: 7.0997 - val_accuracy: 0.7969 - val_loss: 8.9644
Epoch 50/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6875 - loss: 6.8208 - val_accuracy: 0.7962 - val_loss: 4.2118
Epoch 51/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6772 - loss: 5.4771 - val_accuracy: 0.7987 - val_loss: 7.7635
Epoch 52/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6914 - loss: 7.3642 - val_accuracy: 0.7969 - val_loss: 5.8893
Epoch 53/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6851 - loss: 6.9088 - val_accuracy: 0.7950 - val_loss: 2.5445
Epoch 54/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7049 - loss: 4.1322 - val_accuracy: 0.3250 - val_loss: 9.5996
Epoch 55/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6821 - loss: 7.4267 - val_accuracy: 0.7987 - val_loss: 9.3022
Epoch 56/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6862 - loss: 7.4481 - val_accuracy: 0.6963 - val_loss: 1.8825
Epoch 57/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6807 - loss: 7.4036 - val_accuracy: 0.7987 - val_loss: 1.6067
Epoch 58/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6966 - loss: 5.0702 - val_accuracy: 0.7962 - val_loss: 14.1957
Epoch 59/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7127 - loss: 8.8274 - val_accuracy: 0.7544 - val_loss: 2.3179
Epoch 60/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6675 - loss: 5.1263 - val_accuracy: 0.7987 - val_loss: 8.0709
Epoch 61/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7019 - loss: 6.9835 - val_accuracy: 0.7969 - val_loss: 8.4329
Epoch 62/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6815 - loss: 9.2544 - val_accuracy: 0.2537 - val_loss: 6.7273
Epoch 63/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6863 - loss: 5.7457 - val_accuracy: 0.7969 - val_loss: 8.4107
Epoch 64/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6925 - loss: 6.0771 - val_accuracy: 0.7937 - val_loss: 5.5919
Epoch 65/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7181 - loss: 7.6881 - val_accuracy: 0.4869 - val_loss: 5.0306
Epoch 66/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6734 - loss: 6.5011 - val_accuracy: 0.7987 - val_loss: 2.9199
Epoch 67/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6992 - loss: 5.0864 - val_accuracy: 0.4650 - val_loss: 5.5265
Epoch 68/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6706 - loss: 7.0445 - val_accuracy: 0.7600 - val_loss: 3.7124
Epoch 69/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6875 - loss: 5.3560 - val_accuracy: 0.7987 - val_loss: 7.4537
Epoch 70/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6974 - loss: 3.6927 - val_accuracy: 0.2506 - val_loss: 10.7838
Epoch 71/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6708 - loss: 4.6856 - val_accuracy: 0.7975 - val_loss: 5.3477
Epoch 72/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7101 - loss: 3.9729 - val_accuracy: 0.7950 - val_loss: 3.9596
Epoch 73/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7082 - loss: 3.5175 - val_accuracy: 0.7981 - val_loss: 2.7058
Epoch 74/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6939 - loss: 5.0034 - val_accuracy: 0.7975 - val_loss: 2.1863
Epoch 75/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7221 - loss: 5.6501 - val_accuracy: 0.4675 - val_loss: 14.3520
Epoch 76/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6817 - loss: 6.8470 - val_accuracy: 0.3219 - val_loss: 8.6217
Epoch 77/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6744 - loss: 7.9747 - val_accuracy: 0.7969 - val_loss: 10.9821
Epoch 78/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6955 - loss: 6.5107 - val_accuracy: 0.4444 - val_loss: 4.3306
Epoch 79/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6927 - loss: 3.9815 - val_accuracy: 0.7987 - val_loss: 9.5733
Epoch 80/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6984 - loss: 6.1784 - val_accuracy: 0.8000 - val_loss: 3.6365
Epoch 81/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7033 - loss: 4.7153 - val_accuracy: 0.7962 - val_loss: 1.7727
Epoch 82/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6928 - loss: 3.1982 - val_accuracy: 0.7950 - val_loss: 7.1519
Epoch 83/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6946 - loss: 4.2442 - val_accuracy: 0.3731 - val_loss: 4.0105
Epoch 84/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6963 - loss: 3.0551 - val_accuracy: 0.4225 - val_loss: 2.0850
Epoch 85/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6874 - loss: 6.5159 - val_accuracy: 0.7969 - val_loss: 6.0452
Epoch 86/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7052 - loss: 7.2718 - val_accuracy: 0.7969 - val_loss: 4.7924
Epoch 87/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7202 - loss: 4.1522 - val_accuracy: 0.7000 - val_loss: 1.8839
Epoch 88/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7263 - loss: 4.2104 - val_accuracy: 0.6844 - val_loss: 2.5951
Epoch 89/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7198 - loss: 4.3014 - val_accuracy: 0.7981 - val_loss: 4.1474
Epoch 90/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7283 - loss: 3.4173 - val_accuracy: 0.4675 - val_loss: 7.0992
Epoch 91/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7032 - loss: 5.0959 - val_accuracy: 0.5431 - val_loss: 2.0638
Epoch 92/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6832 - loss: 3.8495 - val_accuracy: 0.5444 - val_loss: 1.5862
Epoch 93/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6937 - loss: 2.5893 - val_accuracy: 0.7969 - val_loss: 1.3201
Epoch 94/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7012 - loss: 7.6706 - val_accuracy: 0.7969 - val_loss: 2.9223
Epoch 95/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7172 - loss: 4.9938 - val_accuracy: 0.5406 - val_loss: 1.8825
Epoch 96/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6977 - loss: 3.3313 - val_accuracy: 0.7669 - val_loss: 2.2932
Epoch 97/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7253 - loss: 4.3897 - val_accuracy: 0.7956 - val_loss: 3.5115
Epoch 98/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7110 - loss: 3.1039 - val_accuracy: 0.6706 - val_loss: 1.1897
Epoch 99/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7146 - loss: 2.6564 - val_accuracy: 0.7294 - val_loss: 1.1447
Epoch 100/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7200 - loss: 3.0521 - val_accuracy: 0.7987 - val_loss: 3.9402

In [ ]:
y_pred = model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [ ]:
y_pred

array([[1.6136671e-09],
       [1.4362594e-01],
       [1.4362594e-01],
       ...,
       [1.4362594e-01],
       [1.4362594e-01],
       [3.3389665e-12]], dtype=float32)

In [ ]:
y_pred = y_pred.argmax(axis=-1)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8035

In [ ]:
import numpy as np

print("Please provide the following information:")
credit_score = float(input("Credit Score: "))
age = float(input("Age: "))
tenure = float(input("Tenure: "))
balance = float(input("Balance: "))
num_of_products = float(input("Number of Products: "))
has_credit_card = float(input("Has Credit Card (1 for Yes, 0 for No): "))
is_active_member = float(input("Is Active Member (1 for Yes, 0 for No): "))
estimated_salary = float(input("Estimated Salary: "))
geography = input("Geography (Germany: 1, France: 0): ")
gender = input("Gender (Male: 1, Female: 0): ")

geography_mapping = {'France':[1,0], 'Germany':[0,1], 'Spain':[0,1]}
gender_mapping = {'male':1, 'female':0}
#The issue was on this line, 'grt' should be 'get'
encoded_geography = geography_mapping.get(geography,[0,0])
encoded_gender = gender_mapping.get(gender,[0])

user_input = np.array([[credit_score, age, tenure, balance, num_of_products, has_credit_card, is_active_member, estimated_salary] + encoded_geography + encoded_gender])

user_input_scaled = scaler.transform(user_input)

prediction = model.predict(user_input_scaled)
predicted_class = int(prediction[0][0] > 0.5)

labels = {1: "Person will leave", 0: "Person will not leave"}
print("Churn Prediction:", labels[predicted_class])

Please provide the following information:
Credit Score: 800
Age: 22
Tenure: 5
Balance: 100000
Number of Products: 2
Has Credit Card (1 for Yes, 0 for No): 1
Is Active Member (1 for Yes, 0 for No): 1
Estimated Salary: 10000
Geography (Germany: 1, France: 0): 1
Gender (Male: 1, Female: 0): 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
Churn Prediction: Person will not leave

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
import numpy as np

# Take user input for relevant features
print("Please provide the following details for prediction:")
credit_score = float(input("Credit Score: "))
age = float(input("Age: "))
tenure = float(input("Tenure: "))
balance = float(input("Balance: "))
num_of_products = float(input("Number of Products: "))
has_credit_card = float(input("Has Credit Card (1 for Yes, 0 for No): "))
is_active_member = float(input("Is Active Member (1 for Yes, 0 for No): "))
estimated_salary = float(input("Estimated Salary: "))
geography = input("Geography (France, Germany, Spain): ")
gender = input("Gender (Male, Female): ")

# Encode categorical variables
geography_mapping = {'France': [1, 0], 'Germany': [0, 1], 'Spain': [0, 0]}
gender_mapping = {'Male': [1], 'Female': [0]}
encoded_geography = geography_mapping.get(geography, [0, 0])
encoded_gender = gender_mapping.get(gender, [0])

# Combine all features into an input array
user_input = np.array([[credit_score, age, tenure, balance, num_of_products, has_credit_card,
                        is_active_member, estimated_salary] + encoded_geography + encoded_gender])

# Feature scaling
user_input_scaled = scaler.transform(user_input)

# Make prediction
prediction = model.predict(user_input_scaled)

# Define labels
labels = {1: "Person will leave", 0: "Person will not leave"}

print("Churn Prediction:", labels[int(prediction[0, 0])])

Please provide the following information:
Credit Score: 800
Age: 22
Tenure: 5
Balance: 10000
Number of Products: 2
Has Credit Card (1 for Yes, 0 for No): 1
Is Active Member (1 for Yes, 0 for No): 1
Estimated Salary: 10000
Geography (Germany: 1, France: 0): 1
Gender (Male: 1, Female: 0): 1

AttributeError: 'dict' object has no attribute 'grt'